stages:
  - stage: PrepareStage
    jobs: 
    - job: PrepareJob
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - checkout: self
          path: s/source
        - checkout: build
          path: s/build
        - powershell: | 
            Get-ChildItem env:
          displayName: Display Envrionment Varaibles 
        - powershell: |
            $Env:SEARCHFOR.Split(',') | foreach { Get-ChildItem -r "$_" | % { $_.FullName } }
          displayName: Locate Build Files
