stages:
  - stage: PrepareStage
    jobs: 
    - job: PrepareJob
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - checkout: self
          path: s/source
        - checkout: build
          path: s/build
        - powershell: | 
            echo "$Env:SEARCHFOR".Split(',')
            pwd
            echo "Listing Files"
            ls -r | foreach { $_.FullName }
            # $Env:SEARCHFOR.Split(',') | % { Get-ChildItem -r "$_" | % { $_.FullName } }
            echo "END Listing Files"
          displayName: List Directory Contents
