stages:
  - stage: PrepareStage
    jobs: 
    - job: PrepareJob
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - checkout: self
          path: s/source
        - checkout: build
          path: s/build
        - powershell: | 
            echo "Finding Files"
            $Env:SEARCHFOR.Split(',') | foreach { Get-ChildItem -r "$_" | % { $_.FullName } }
          displayName: List Directory Contents
