stages:
  - stage: PrepareStage
    jobs: 
    - job: PrepareJob
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - checkout: self
          path: s/source
        - checkout: build
          path: s/build
        - checkout: tools
          path: s/tools
        - powershell: | 
            Get-ChildItem env:
          displayName: Display Envrionment Varaibles 
        - powershell: |
            if (!(Test-Path "$Env:BUILD_ARTIFACTSTAGINGDIRECTORY/build" )) { mkdir "$Env:BUILD_ARTIFACTSTAGINGDIRECTORY/build" }
            $Env:SEARCHFOR.Split(',') | foreach { Get-ChildItem -r "$_" | % { $_.FullName } } > "$Env:BUILD_ARTIFACTSTAGINGDIRECTORY/build/build.lst"
            echo "Located the following build files"
            cat "$Env:BUILD_ARTIFACTSTAGINGDIRECTORY/build/build.lst"
          displayName: Locate Build Files
        - bash: dotnet build tools
          displayName: Create Build Tools
        - bash: |
            echo "Building Map"
            cat "$BUILD_ARTIFACTSTAGINGDIRECTORY/build/build.lst" | dotnet tools/DotNetCoreBuildTools/bin/Debug/netcoreapp3.1/DotNetCoreBuildTools.dll > "$BUILD_ARTIFACTSTAGINGDIRECTORY/build/projects.map"
            echo "Outputing Map"
            ls -l "$BUILD_ARTIFACTSTAGINGDIRECTORY/build/projects.map"
            cat "$BUILD_ARTIFACTSTAGINGDIRECTORY/build/projects.map"
          displayName: Generating Project Map
